java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: ${SERVICE_NAME}-postgresql
    POSTGRES_NAME: ia-case-api
    POSTGRES_USERNAME: hmcts
    POSTGRES_PASSWORD: hmcts
    POSTGRES_CONNECTION_OPTIONS: ""
    IA_CASE_DOCUMENTS_API_URL: "http://ia-case-documents-api-aat.service.core-compute-aat.internal/"
    IA_CASE_NOTIFICATIONS_API_URL: "http://ia-case-notifications-api-aat.service.core-compute-aat.internal/"
    IA_TIMED_EVENT_SERVICE_URL: "http://ia-timed-event-service-aat.service.core-compute-aat.internal/"
    IA_TIMED_EVENT_SERVICE_ENABLED: "false"
    IA_CASE_PAYMENTS_API_URL: "http://ia-case-payments-api-aat.service.core-compute-aat.internal/"
    IA_HOME_OFFICE_INTEGRATION_API_URL: "http://ia-home-office-integration-api-aat.service.core-compute-aat.internal/"
    IA_HOME_OFFICE_INTEGRATION_ENABLED: "false"
    IA_IDAM_REDIRECT_URI: "https://ia-case-api-aat.service.core-compute-aat.internal/oauth2/callback"
    CCD_URL: "http://{{ .Release.Name }}-ccd-data-store-api"
    CCD_GW_URL: "http://dm-store-aat.service.core-compute-aat.internal"
    DM_URL: "http://dm-store-aat.service.core-compute-aat.internal"
    IDAM_URL: "https://idam-api.aat.platform.hmcts.net"
    OPEN_ID_IDAM_URL: "https://idam-web-public.aat.platform.hmcts.net"
    S2S_URL: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
    IS_SAVE_AND_CONTINUE_ENABLED: "false"
    ROLE_ASSIGNMENT_URL: "http://am-role-assignment-service-aat.service.core-compute-aat.internal"
  keyVaults:
    ia:
      secrets:
        - docmosis-enabled
        - em-stitching-enabled
        - submit-hearing-requirements-enabled
        - system-username
        - system-password
        - idam-client-id
        - idam-secret
        - s2s-secret
        - s2s-microservice
        - prof-ref-data-url
        - docmosis-enabled
        - em-stitching-enabled
        - launch-darkly-sdk-key
  postgresql:
    enabled: true
    image:
      tag: '11.6.0'
    primary:
      persistence:
        enabled: false
      resources:
        requests:
          cpu: 25m
      initdb:
        scripts:
          init.sql: |
            CREATE DATABASE "ia-case-api" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
            CREATE DATABASE "data-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
            CREATE DATABASE "definition-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
            CREATE DATABASE "role_assignment" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
            CREATE DATABASE "user-profile" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
    auth:
      username: hmcts
      password: hmcts

idam-pr:
  releaseNameOverride: ${SERVICE_NAME}-idam-pr
  enabled: true
  redirect_uris:
    XUI:
      - https://xui-${SERVICE_FQDN}/oauth2/callback
    CCD Admin:
      - https://admin-web-${SERVICE_FQDN}/oauth2redirect
    ccd_data_store_api:
      - https://ccd-data-store-api-${SERVICE_FQDN}/oauth2redirect

xui-webapp:
  enabled: true
  nodejs:
    imagePullPolicy: Always
    releaseNameOverride: ${SERVICE_NAME}-xui-webapp
    image: hmctspublic.azurecr.io/xui/webapp:latest
    ingressHost: xui-${SERVICE_FQDN}
    memoryLimits: 1836Mi
    cpuLimits: 1900m
    environment:
      HEALTH_CCD_COMPONENT_API: http://gateway-${SERVICE_FQDN}/health
      HEALTH_CCD_DATA_API: https://ccd-data-store-api-${SERVICE_FQDN}/health
      HEALTH_TERMS_AND_CONDITIONS_API: https://xui-terms-and-conditions-${SERVICE_FQDN}/health
      SERVICES_EM_ANNO_API: http://{{ .Release.Name }}-ccd-api-gw
      SERVICES_CCD_COMPONENT_API: http://{{ .Release.Name }}-ccd-api-gw
      SERVICES_CCD_DATA_STORE_API: http://{{ .Release.Name }}-ccd-data-store-api
      SERVICES_TERMS_AND_CONDITIONS: https://xui-terms-and-conditions-${SERVICE_FQDN}
      SERVICES_IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
      SERVICES_S2S: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      SERVICES_PRD_LOCATION_API: http://rd-location-ref-api-aat.service.core-compute-aat.internal
      SERVICES_PRD_JUDICIAL_API: http://rd-judicial-api-aat.service.core-compute-aat.internal
      SERVICES_PRD_COMMONDATA_API: http://rd-commondata-api-aat.service.core-compute-aat.internal
      SERVICES_CCD_CASE_ASSIGNMENT_API: https://aac-${SERVICE_FQDN}
      JURISDICTIONS: IA
      LAUNCH_DARKLY_CLIENT_ID: 5de6610b23ce5408280f2268
      FEATURE_REDIS_ENABLED: false
      FEATURE_APP_INSIGHTS_ENABLED: false
      FEATURE_SECURE_COOKIE_ENABLED: false
      FEATURE_PROXY_ENABLED: false
      FEATURE_TERMS_AND_CONDITIONS_ENABLED: false
      FEATURE_HELMET_ENABLED: false
      FEATURE_OIDC_ENABLED: false
      NOW: false
      REDISCLOUD_URL: http://dummyrediscloudurl
      UV_THREADPOOL_SIZE: 128
      PROTOCOL: http
    keyVaults:
      rpx:
        resourceGroup: rpx
        secrets:
          - mc-s2s-client-secret
          - mc-idam-client-secret
          - system-user-name
          - system-user-password

ia-case-payments-api:
  enabled: true
  nodejs:
    imagePullPolicy: Always
    image: 'hmctspublic.azurecr.io/ia/ia-case-payments-api:latest'
    releaseNameOverride: ${SERVICE_NAME}-ia-case-payments
    ingressHost: ia-payments-api-${SERVICE_FQDN}
    environment:
      IDAM_URL: https://idam-api.aat.platform.hmcts.net
      S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      FEES_REGISTER_API_URL: http://fees-register-api-aat.service.core-compute-aat.internal
      PAYMENT_API_URL: http://payment-api-aat.service.core-compute-aat.internal
      PAY_CALLBACK_URL: https://ia-payments-api-${SERVICE_FQDN}/service-request-update
      PROF_REF_DATA_URL: http://rd-professional-api-aat.service.core-compute-aat.internal"
      CCD_URL: http://{{ .Release.Name }}-ccd-data-store-api
    keyVaults: []

ccd:
  enabled: true
  ccd:
    adminWeb:
      enabled: true
    managementWeb:
      enabled: false
    definitionImporter:
      enabled: false
    userProfileImporter:
      enabled: false
    apiGatewayWeb:
      enabled: true
    postgresql:
      enabled: false
    s2s:
      enabled: false
    elastic:
      enabled: true
    ras:
      enabled: false
  global:
    ccdApiGatewayIngress: http://{{ .Release.Name }}-ccd-api-gw
    ccdAdminWebIngress: admin-web-${SERVICE_FQDN}
    ccdDataStoreUrl: http://{{ .Release.Name }}-ccd-data-store-api
    ccdDefinitionStoreUrl:  http://{{ .Release.Name }}-ccd-definition-store
    # Enable this to use a local ccd user profile importer
    # ccdUserProfileUrl: http://${SERVICE_NAME}-ccd-user-profile-api
    ccdUserProfileUrl: http://ccd-user-profile-api-aat.service.core-compute-aat.internal
    dmStoreUrl: http://dm-store-aat.service.core-compute-aat.internal
    idamApiUrl: https://idam-api.aat.platform.hmcts.net
    idamWebUrl: https://idam-web-public.aat.platform.hmcts.net
    s2sUrl: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    enableKeyVaults: true
    devMode: true

  ccd-api-gateway-web:
    nodejs:
      imagePullPolicy: Always
      environment:
        ADDRESS_LOOKUP_TOKEN: ${ADDRESS_LOOKUP_TOKEN}
        IDAM_SERVICE_KEY: ${API_GATEWAY_S2S_KEY}
        IDAM_OAUTH2_CLIENT_SECRET: ${CCD_API_GATEWAY_IDAM_CLIENT_SECRET}
        PROXY_DOCUMENT_MANAGEMENT: http://dm-store-aat.service.core-compute-aat.internal
      ingressHost: gateway-${SERVICE_FQDN}
      ingressIP: ${INGRESS_IP}

  ccd-data-store-api:
    java:
      imagePullPolicy: Always
      devcpuRequests: 500m
      devmemoryRequests: 2048Mi
      devmemoryLimits: 4096Mi
      autoscaling:
        enabled: false
      disableKeyVaults: true
      environment:
        DATA_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DATA_STORE_DB_USERNAME: hmcts
        DATA_STORE_DB_PASSWORD: hmcts
        DATA_STORE_IDAM_KEY: ${DATA_STORE_S2S_KEY}
        DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_gw,ccd_gateway,ccd_data,ccd_ps,aac_manage_case_assignment,xui_webapp,ccd_case_document_am_api,ia
        #CCD_S2S_AUTHORISED_SERVICES_CASE_USER_ROLES: aac_manage_case_assignment,ia, iac #ET don't have this
        IDAM_API_BASE_URL: https://idam-api.aat.platform.hmcts.net
        IDAM_OIDC_URL: https://idam-web-public.aat.platform.hmcts.net
        IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET: ${IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET}
        IDAM_DATA_STORE_SYSTEM_USER_USERNAME: ${IDAM_DATA_STORE_SYSTEM_USER_USERNAME}
        IDAM_DATA_STORE_SYSTEM_USER_PASSWORD: ${IDAM_DATA_STORE_SYSTEM_USER_PASSWORD}
        CASE_DOCUMENT_AM_URL: http://ccd-case-document-am-api-aat.service.core-compute-aat.internal
        ROLE_ASSIGNMENT_URL: http://am-role-assignment-service-aat.service.core-compute-aat.internal
        ELASTIC_SEARCH_ENABLED: true
        ELASTIC_SEARCH_HOSTS: ${SERVICE_NAME}-es-master:9200
        ELASTIC_SEARCH_DATA_NODES_HOSTS: http://${SERVICE_NAME}-es-master:9200
        ENABLE_ATTRIBUTE_BASED_ACCESS_CONTROL: true
        ENABLE_PSEUDO_ROLE_ASSIGNMENTS_GENERATION: true
        ENABLE_PSEUDO_ACCESS_PROFILES_GENERATION: true
      keyVaults: []
      ingressHost: ccd-data-store-api-${SERVICE_FQDN}

  ccd-admin-web:
    nodejs:
      image: hmctspublic.azurecr.io/ccd/admin-web:latest
      ingressHost: admin-web-${SERVICE_FQDN}
      environment:
        IDAM_ADMIN_WEB_SERVICE_KEY: ${ADMIN_S2S_KEY}
        IDAM_OAUTH2_AW_CLIENT_SECRET: ${ADMIN_WEB_IDAM_SECRET}
#        IDAM_BASE_URL: https://idam-api.aat.platform.hmcts.net
#        IDAM_OAUTH2_TOKEN_ENDPOINT: https://idam-web-public.aat.platform.hmcts.net/oauth2/token
#        IDAM_S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
#        USER_PROFILE_DB_HOST: ${SERVICE_NAME}-postgresql
      keyVaults: []

  ccd-definition-store-api:
    java:
      image: hmctspublic.azurecr.io/ccd/definition-store-api:latest
      imagePullPolicy: Always
      autoscaling:
        enabled: false
      environment:
        DEFINITION_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DEFINITION_STORE_IDAM_KEY: ${DEFINITION_STORE_S2S_KEY}
        IDAM_USER_URL: https://idam-web-public.aat.platform.hmcts.net
        DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_gw,ccd_admin,ccd_gateway,ccd_data,ccd_ps,aac_manage_case_assignment,xui_webapp,ia,em_ccd_orchestrator,ccd_case_document_am_api
        OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat2.internal:8443/openam/oauth2/hmcts
        ELASTIC_SEARCH_ENABLED: true
        ELASTIC_SEARCH_HOST: ${SERVICE_NAME}-es-master
        ELASTIC_SEARCH_FAIL_ON_IMPORT: false
        USER_PROFILE_HOST: http://ccd-user-profile-api-aat.service.core-compute-aat.internal
      keyVaults: [ ]
      ingressHost: ccd-definition-store-${SERVICE_FQDN}
  postgresql:
    persistence:
      enabled: false

  elasticsearch:
    nameOverride: ${SERVICE_NAME}-es
    clusterName: es
    replicas: 1

  logstash:
    image: null
    tag: ccd-cmc-logstash-latest

